edition = "2021"

max_width = 120

indent_style = "Block"

## imports ##
reorder_imports = true
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
imports_granularity = "module"
